name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: tools/explorer
    - uses: pnpm/action-setup@v4.0.0
      with:
        package_json_file: tools/explorer/package.json
        run_install: true

    - name: build
      working-directory: tools/explorer
      run: |
        pnpm build
    
    - uses: actions/upload-artifact@v4
      with:
        path: tools/explorer/dist
